<CODE> -> <10><IF>|<10><CODE><IF>.
<IF> -> <10>if <COND> {<ACTION>} else {<ACTION>} | <10>if <COND> { <ACTION> }.
<COND> -> <10>'('<OBS>')' | <10>'('<OBS><CONDOP><OBS>')'.
<OBS> -> <10><CLAZZ>'.equals(this.getObservation("type' <DIR> '"))'.
<CLAZZ> -> <10>'"PasiveEntity"' | <10>'"MyIndividual"'.
<CONDOP> -> <10>'&&'|<10>'||'.
<ACTION> -> <10>'return ' <AS> ';'.
<AS> -> <10>'"chase'<DIR>'"' | <10>'"runaway'<DIR>'"' .
<DIR> -> <100>'UP'|<100>'DOWN'|<100>'LEFT'|<100>'RIGHT'.