package simulator.model.map.creator;

/**
*
* @author fabrizioortega
*/
/**
*
* @author fabrizioortega
*/
public class MapCreator extends javax.swing.JFrame {

   /**
    * Creates new form MapCreator
    */
   public MapCreator() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jtpMainPanel = new javax.swing.JTabbedPane();
       terrainPanel = new TerrainPanel();
       attributesPanel = new AttributesPanel();
       elevationPanel = new ElevationPanel();
       jMenuBar1 = new javax.swing.JMenuBar();
       jMenu1 = new javax.swing.JMenu();
       jmiOpen = new javax.swing.JMenuItem();
       jmiSave = new javax.swing.JMenuItem();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setMaximumSize(new java.awt.Dimension(1400, 750));
       setMinimumSize(new java.awt.Dimension(1400, 750));

       jtpMainPanel.addTab("Attributes", attributesPanel);
       jtpMainPanel.addTab("Terrain", terrainPanel);
       jtpMainPanel.addTab("Elevation", elevationPanel);

       jMenu1.setText("File");

       jmiOpen.setText("Open");
       jmiOpen.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jmiOpenActionPerformed(evt);
           }
       });
       jMenu1.add(jmiOpen);

       jmiSave.setText("Save");
       jmiSave.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jmiSaveActionPerformed(evt);
           }
       });
       jMenu1.add(jmiSave);

       jMenuBar1.add(jMenu1);

       setJMenuBar(jMenuBar1);

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jtpMainPanel))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jtpMainPanel, javax.swing.GroupLayout.Alignment.TRAILING)
       );

       pack();
   }// </editor-fold>                        

   private void jmiOpenActionPerformed(java.awt.event.ActionEvent evt) {                                        
       // TODO add your handling code here:
   }                                       

   private void jmiSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
       // TODO add your handling code here:
   }                                       

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(MapCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new MapCreator().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private AttributesPanel attributesPanel;
   private ElevationPanel elevationPanel;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jmiOpen;
   private javax.swing.JMenuItem jmiSave;
   private javax.swing.JTabbedPane jtpMainPanel;
   private TerrainPanel terrainPanel;
   // End of variables declaration                   
}

