package genome_editing.model;

import java.awt.Dimension;

public class Editor extends javax.swing.JPanel {

    /**
     * Creates new form GenomeEditor
     */
    public Editor(Dimension dim) {
    	 setMaximumSize(dim);
         setMinimumSize(dim);
         this.setPreferredSize(dim);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

       

    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}