package post_analysis;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.Future;

import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.json.JSONTokener;

import post_analysis.fitness_tests.SimpleMazeFitnessTest;

public class SimulationAnalysis extends javax.swing.JFrame {
	private DefaultTableModel tableModel;
	private Vector<Vector<Object>> data;
	private JSONArray entities;
    /**
     * Creates new form SimulationAnalysis
     */
    public SimulationAnalysis() {
        initComponents();
        _config();
    }

    private void _config() {
    	setData("resources/loads/simulations/filename.json");

    	Vector<String> header = new Vector<String>();
    	header.add("id");
    	header.add("age");
    	header.add("fitness");
    	tableModel.setDataVector(data, header);
    	jTable1.setCellSelectionEnabled(true);
    	
		ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
		cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
		        public void valueChanged(ListSelectionEvent e) {
		        	_selectionChanged(jTable1.getSelectedRow());
	
		
		        }
		});
		
		class Task implements Callable<Integer>{
			JSONObject e;
			public Task(JSONObject e) {
				this.e=e;
			}
			@Override
			public Integer call() throws Exception {
				return new SimpleMazeFitnessTest(1000).evaluate(e);
			}
			
		}
    	List<Task>tasks = new ArrayList<Task>();
    	for(int i=0;i<this.entities.length();i++) {
    		tasks.add(new Task(this.entities.getJSONObject(i)));
    	}
    	ExecutorService service = Executors.newCachedThreadPool();
    	List<Future<Integer>> results;
		try {
			results = service.invokeAll(tasks);
			for(int i=0;i<results.size();i++) {
	    		try {
					this.data.get(i).set(2,results.get(i).get().intValue());
				} catch (InterruptedException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} catch (ExecutionException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
	    	}
		} catch (InterruptedException e2) {
			// TODO Auto-generated catch block
			e2.printStackTrace();
		}
		finally {
			service.shutdown();
		}
    	
	}
    
    private void setData(String fileName) {
    	try {
			JSONObject o = new JSONObject(new JSONTokener(new FileInputStream(fileName)));
			JSONArray arr = o.getJSONArray("entities");
			entities = new JSONArray();
			data = new Vector<Vector<Object>>(arr.length());
			for(int i = 0; i<arr.length(); i++) {
				Vector<Object>v = new Vector<Object>();
				if(arr.getJSONObject(i).getString("type").equals("f"))continue;
				entities.put(arr.getJSONObject(i));
				v.add(arr.getJSONObject(i).getJSONObject("data").getString("id"));
				v.add(arr.getJSONObject(i).getJSONObject("data").getInt("age"));

				data.add(v);
			}
			
		} catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    private void _selectionChanged(int selectedRow) {
		// TODO Auto-generated method stub
    	JLabel label = new JLabel();
    	label.setText("<html>" + this.entities.getJSONObject(selectedRow).getJSONObject("data").getJSONObject("phenotype").getString("code").replaceAll("<","&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br/>").replaceAll("    ", "&emsp ") + "</html>");
    	//label.setAlignmentX(Component.RIGHT_ALIGNMENT);
    	//label.setAlignmentY(Component.TOP_ALIGNMENT);
    	
		this.visualizationPane.setViewportView(label);
		
    	/*SimpleMazeFitnessTest t = new SimpleMazeFitnessTest(this.visualizationPane);
    	t.evaluate(this.entities.getJSONObject(selectedRow));*/
	}
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	tableModel = new DefaultTableModel(0,0);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(tableModel);
        visualizationPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

      
        jScrollPane1.setViewportView(jTable1);

        visualizationPane.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(visualizationPane, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(visualizationPane))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationAnalysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane visualizationPane;
    // End of variables declaration                   
}

