<CODE> -> <LINE>.
<LINE> -> <ACTION>;|<IF>.
<IF> -> if <COND> {<LINE>} else {<LINE>} | if <COND> { <LINE> }.
<COND> -> (<OBS>).
<OBS> -> 'this.getAttribute('<PAIRGETATT>.
<PAIRGETATT> -> '"personality")=="hunger"'.
<ACTION> -> 'this.setAttribute('<PAIRSETATT>')'.
<PAIRSETATT> -> '"personality","hunger"'.
<LOGOP> -> '||' | &&.